// Lista consolidada de instituições para cadastro de itens
// Mantida em ordem alfabética aproximada, sem duplicidades
(function () {
  window.INSTITUICOES = [
    "ACAFE",
    "AFA",
    "Albert Einstein",
    "Anhembi Morumbi Medicina",
    "Autoral",
    "Campo Real Medicina",
    "CEFET",
    "Cefet-PR",
    "CEFSA",
    "CEPERJ",
    "Cesgranrio",
    "CESMAC",
    "CESUPA",
    "CMRJ",
    "Colégio Embraer",
    "Colégio Objetivo",
    "COLTEC",
    "COMAGSUL - PE",
    "COTUCA",
    "CTI",
    "CUSC",
    "EAM",
    "EBMSP",
    "ECM-AL",
    "EDUCA",
    "EEAR",
    "EFOMM",
    "EMESCAM",
    "EN",
    "ENCCEJA",
    "ENEM",
    "ENEM COP30",
    "ENEM Digital",
    "ENEM libras",
    "ENEM PPL",
    "EPCAR",
    "ESA",
    "Esam",
    "EsPCEx",
    "ESPM",
    "ETEC",
    "EVO Concursos",
    "FAAP",
    "FACERES",
    "FACISA",
    "FACISB",
    "Faetec",
    "Fafeod-MG",
    "FAG Demais Cursos",
    "FAG Medicina",
    "FAGOC",
    "FAI",
    "FAME",
    "FAMECA",
    "FAMEMA",
    "FAMERP",
    "FAMP",
    "FASA",
    "FASM",
    "FATEC",
    "FCMMG",
    "FCM PB",
    "FCMSJF",
    "FCSB",
    "FDV",
    "FEI-SP",
    "FUNIVERSA",
    "FURRN",
    "FUVEST",
    "Humanitas",
    "IBFC",
    "IFAL",
    "IFES",
    "IFNMG",
    "IFPE",
    "IFPI",
    "IFPR",
    "IFRN",
    "IFRR",
    "IFRS",
    "IFSudesteMG",
    "IFSulDeMinas",
    "IFTM",
    "IFTO",
    "IME",
    "IMEPAC",
    "INSPER",
    "Instituto Access",
    "Instituto Fênix",
    "ITA",
    "ITE-SP",
    "MACKENZIE",
    "Mandic",
    "Multivix",
    "OBB",
    "OBF",
    "OBMEP",
    "OBQ",
    "PAS - UFLA",
    "PUC-Campinas",
    "PUC-GO",
    "PUC-MG",
    "PUC-PR",
    "PUC-RJ",
    "PUC-RS INVERNO",
    "PUC-RS VERÃO",
    "PUC-SP",
    "SANTA CASA",
    "Santo Agostinho",
    "SEDUC - SP",
    "Suprema Medicina",
    "UCDB-MS",
    "UCPEL",
    "UCS",
    "UCSal-BA",
    "UDESC",
    "UEA",
    "UECE",
    "UEFS",
    "UEG",
    "UEL",
    "UEM",
    "UEMA",
    "UEMA PAES",
    "UEMG",
    "UEMS",
    "UENP",
    "UEPA",
    "UEPB",
    "UEPG-PR",
    "UEPI",
    "UERJ",
    "UERN",
    "UERR",
    "UESB",
    "UFABC",
    "UFAC",
    "UFAL",
    "UFAM",
    "UFC",
    "UFCA",
    "UFCSPA",
    "UFF",
    "UFFS",
    "UFG",
    "UFGD",
    "UFJF",
    "UFLA-MG",
    "UFMG",
    "UFMS",
    "UFMS PASSE",
    "UFMT",
    "UFN",
    "UFPA",
    "UFPB",
    "UFPE",
    "UFPel-RS",
    "UFPI",
    "UFPR",
    "UFRGS",
    "UFRJ",
    "UFRN",
    "UFRR",
    "UFRS",
    "UFSCAR",
    "UFSJ",
    "UFSM",
    "UFT",
    "UFTM",
    "UFU",
    "UFV",
    "UFVJM",
    "ULBRA",
    "Unaerp Medicina",
    "UnB",
    "UNCISAL",
    "UNEB",
    "UNEC",
    "UNEMAT",
    "UNESC",
    "UNESP",
    "UNIC",
    "UNICAMP",
    "UNICENTRO",
    "UniCesumar",
    "UniCEUB",
    "Unichristus",
    "UNICID",
    "Unidompedro",
    "UNIEVA",
    "UNIFAA",
    "UNIFAE",
    "UNIFAL",
    "UNIFAN",
    "UNIFENAS",
    "Unifeso",
    "UNIFESP",
    "UNIFIMES",
    "Unifor",
    "UNIFUNEC",
    "Unilago",
    "Unimep",
    "UNIMES",
    "Unimontes",
    "UniNassau",
    "UNINTA",
    "Unioeste",
    "UNIP",
    "UNIPAM",
    "UNIPAR",
    "UnirG",
    "UNI-RIO",
    "UNISA",
    "Unisa-SP",
    "UNISC Medicina",
    "UNISINOS",
    "Unit-AL",
    "UNITAU",
    "UNITINS",
    "Unit-SE",
    "Uniube",
    "UNIVAG",
    "UNIVASF",
    "UNIVESP",
    "UnP Medicina",
    "UPE",
    "UPE SSA",
    "UPF",
    "URCA",
    "USCS",
    "USS",
    "UVA",
    "UVV Medicina",
  ];
})();
